# Generated by Django 3.2 on 2021-04-20 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(13)])),
                ('desc', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
