# Generated by Django 3.2 on 2021-04-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_link',
            field=models.CharField(default='https://m.media-amazon.com/images/I/51V65tyBqNL.jpg', max_length=300),
        ),
    ]
