# Generated by Django 3.2 on 2021-04-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanager', '0002_book_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image_link',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='', upload_to='librarymanager/images'),
        ),
    ]
