# Generated by Django 3.2 on 2021-04-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanager', '0008_alter_issuerequest_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuerequest',
            name='student_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
