# Generated by Django 3.2 on 2021-04-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanager', '0009_issuerequest_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
    ]
