# Generated by Django 3.2 on 2021-04-25 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanager', '0011_approval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuerequest',
            old_name='request_id',
            new_name='request_id_old',
        ),
    ]
