# Generated by Django 3.2 on 2021-04-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanager', '0012_rename_request_id_issuerequest_request_id_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuerequest',
            name='request_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
