# Generated by Django 3.2 on 2021-04-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanager', '0013_issuerequest_request_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuerequest',
            name='request_id',
        ),
    ]
