# Generated by Django 3.2 on 2021-04-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanager', '0014_remove_issuerequest_request_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuerequest',
            old_name='request_id_old',
            new_name='request_id',
        ),
    ]
