# Generated by Django 3.2 on 2021-04-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanager', '0015_rename_request_id_old_issuerequest_request_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approval',
            old_name='request_id',
            new_name='request_id_old',
        ),
    ]
